name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: build dependencies
        run: sudo apt install build-essential git libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev build-essential git
      - name: build for linux
        run: zig build --release=small
      - name: build for windows
        run: zig build --release=small -Dtarget=x86_64-windows
      - name: create artifact
        uses: actions/upload-artifact@v4
        with:
          name: asteroids
          path: zig-out/bin/asteroids
          if-no-files-found: error
          overwrite: true

